In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
conn = sql.connect('factbook.db')
conn

In [3]:
def sql_query(q):
    return pd.read_sql_query(q,conn)

In [7]:
q = 'Select * from facts'
sql_query(q)

,id,code,name,area,area_land,area_water,population,population_growth,birth_rate,death_rate,migration_rate
0,1,af,Afghanistan,652230.0,652230.0,0.0,3.256434e+07,2.32,38.57,13.89,1.51
1,2,al,Albania,28748.0,27398.0,1350.0,3.029278e+06,0.30,12.92,6.58,3.30
2,3,ag,Algeria,2381741.0,2381741.0,0.0,3.954217e+07,1.84,23.67,4.31,0.92
3,4,an,Andorra,468.0,468.0,0.0,8.558000e+04,0.12,8.13,6.96,0.00
4,5,ao,Angola,1246700.0,1246700.0,0.0,1.962535e+07,2.78,38.78,11.49,0.46
...,...,...,...,...,...,...,...,...,...,...,...
256,257,zh,Atlantic Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,258,xo,Indian Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,259,zn,Pacific Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,260,oo,Southern Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,261,xx,World,NaN,NaN,NaN,7.256490e+09,1.08,18.60,7.80,NaN

In [9]:
q = 'Select * from cities'
sql_query(q)

      id          name  population  capital facts_id
0      1    Oranjestad       37000        1      216
1      2  Saint John'S       27000        1        6
2      3     Abu Dhabi      942000        1      184
3      4         Dubai     1978000        0      184
4      5       Sharjah      983000        0      184
..   ...           ...         ...      ...      ...
392  393       Mbabane       66000        1      167
393  394         Sanaa     2419000        1      193
394  395          Aden      784000        0      193
395  396        Lusaka     1802000        1      194
396  397        Harare     1542000        1      195

[397 rows x 5 columns]

### 1. List all cities where the area is greater than 5000, along with their population.

In [10]:
q = ''' select c.name city_name,f.area,f.population from cities c inner join facts f
        on
        c.facts_id = f.id
        where f.area > 5000
'''
sql_query(q)

     city_name     area  population
0    Abu Dhabi    83600     5779760
1        Dubai    83600     5779760
2      Sharjah    83600     5779760
3        Kabul   652230    32564342
4      Algiers  2381741    39542166
..         ...      ...         ...
349    Mbabane    17364     1435613
350      Sanaa   527968    26737317
351       Aden   527968    26737317
352     Lusaka   752618    15066266
353     Harare   390757    14229541

[354 rows x 3 columns]

### 2. List the names of capital cities where the death rate is greater than 2% and the birth rate is less than 20%

In [11]:
q = '''select c.name city_name,f.death_rate,f.birth_rate from cities c inner join facts f
        on
        c.facts_id = f.id
        where f.death_rate > 2
        and
        f.birth_rate < 20
'''
sql_query(q)

            city_name  death_rate  birth_rate
0          Oranjestad        8.18       12.56
1        Saint John'S        5.69       15.85
2                Baku        7.07       16.64
3              Tirana        6.58       12.92
4             Yerevan        9.34       13.61
..                ...         ...         ...
261          Haiphong        5.93       15.96
262           Da Nang        5.93       15.96
263  Charlotte Amalie        8.54       10.31
264          Windhoek       13.91       19.80
265          Mata-Utu        5.06       13.45

[266 rows x 3 columns]

### 3. List the cities with a population growth rate between 1% and 5%, sorted in desc by population growth.

In [12]:
q = '''select c.name city_name, f.population_growth from cities c 
        inner join facts f on
        c.facts_id = f.id
        where f.population_growth between 1 and 5
        order by f.population_growth desc
'''
sql_query(q)

     city_name  population_growth
0         Juba               4.02
1     Lilongwe               3.32
2    Bujumbura               3.28
3       Niamey               3.25
4      Kampala               3.24
..         ...                ...
210        Fes               1.00
211  Marrakech               1.00
212    Tangier               1.00
213     Agadir               1.00
214    Managua               1.00

[215 rows x 2 columns]

### 4. Find countries that start with &quot;A&quot; and do not have any cities listed in the cities table. The query should return the country name and city name. Using left join

In [14]:
q = '''select f.name country_name, c.name city_name from facts f left join 
        cities c on 
        f.id = c.facts_id
        where f.name like "A%"
        and
        c.name is null
'''
sql_query(q)

                  country_name city_name
0  Ashmore and Cartier Islands      None
1                     Akrotiri      None
2                   Antarctica      None
3                 Arctic Ocean      None
4               Atlantic Ocean      None

### 5. List all capital cities and their corresponding death rate using a LEFT JOIN.

In [15]:
q = '''select c.name city_name, c.capital, f.death_rate from cities c left join 
        facts f on 
        c.facts_id = f.id
        where c.capital == 1
'''
sql_query(q)

        city_name  capital  death_rate
0      Oranjestad        1        8.18
1    Saint John'S        1        5.69
2       Abu Dhabi        1        1.97
3           Kabul        1       13.89
4         Algiers        1        4.31
..            ...      ...         ...
203          Apia        1        5.32
204       Mbabane        1       13.56
205         Sanaa        1        6.28
206        Lusaka        1       12.67
207        Harare        1       10.13

[208 rows x 3 columns]